### ISSUE TITLE
Запуск main.lua - ошибка в qlua_pb_init.lua:1: module 'lua-protobuf.protoc' not found

### ISSUE THREAD

**Issue by euvgub** [Enfernuz/quik-lua-rpc#19]
Запуск main.lua - ошибка в qlua_pb_init.lua:1: module 'lua-protobuf.protoc' not found. Просьба добавить в README.md в Установка зависимостей Скопировать репозиторий https://github.com/Enfernuz/lua-protobuf в в %PATH_TO_QUIK%/lua/, где %PATH_TO_QUIK%

**Comment by Enfernuz** [comment]
Обновил `redist.zip` в корне репозитория.
