### ISSUE TITLE
qlua_pb_init.lua:16: attempt to call method 'loadfile' (a nil value)

### ISSUE THREAD

**Issue by euvgub** [Enfernuz/quik-lua-rpc#20]
qlua_pb_init.lua:16: attempt to call method 'loadfile' (a nil value)
В windows не находит путь файлов proto

**Comment by Enfernuz** [comment]
Да, забыл добавить новую protobuf-библиотеку в дистрибутив. Теперь все нужные для работы библиотеки лежат в обновлённом `redist.zip` в корне репозитория. Скомпилированы, правда, под Windows 10. Под более ранние версии скомпилирую чуть позже, на выходных.
