### ISSUE TITLE
send_string конвертит int в string

### ISSUE THREAD

**Issue by euvgub** [Enfernuz/quik-lua-rpc#22]
json и send_string конвертит int в string. Если надо послать сообщение с числовым аргументом, то результат - ошибка. Например в таком сообщении аргумент index, который должен быть integer, шлется string-ом 
socket.send_string("{\"method\":\"getItem\", \"args\":{\"table_name\":\"client_codes\",\"index\":3}}")

**Comment by euvgub** [comment]
Похоже просто в qlua_structures не прописана таблица client_codes из числа таблиц, используемых в функциях «getItem», «getNumberOf».

**Comment by Enfernuz** [comment]
Не понял немного. Формирование JSON-строки запроса на клиентской стороне полностью лежит на клиентском коде, сервис тут не при чём.

Насчёт парсинга JSON-строки запроса на стороне сервиса: в текущей реализации пришедшая из ZeroMQ-сокета строка подаётся на вход декодеру библиотеки https://github.com/rxi/json.lua, у декодированной таблицы берётся объект "args" и подаётся на вход врапперу процедуры (https://github.com/Enfernuz/quik-lua-rpc/blob/1a494c66cbf92cb5695d39ea20595519534b44bf/impl/procedure_wrappers.lua#L91). Т.е. никакой дополнительной магии над запросом не производится.

Что касается таблицы client_codes: насколько я помню, её структуры нет в документации. А реализация удалённой процедуры сделана таким образом, что любую таблицу, пришедшую из getItem, оборачивает в таблицу вида (key = string, value = string) -- это сделано потому, что проще возложить парсинг результата на клиента, чем разбирать все случаи в сервиса, к тому же нет желания при добавлении новых таблиц потом редактировать код их обработки в сервисе (ну и, плюсом к этому, вышеупомянутое отсутствие в документации структуры некоторых таблиц).

**Comment by euvgub** [comment]
Это какая-то особенность конкретной таблицы client_codes. На запрос socket.send_string("{"method":"getItem", "args":{"table_name":"client_codes","index":тут число}}") она отдает error code 1. Все другие таблицы нормально отдают все свои table_rows.
Причем на чистом lua эта таблица client_codes нормально отдает строки 
local n = getNumberOf("client_codes")
message("Number of accounts is " .. tostring(n))
for i=0,n-1,1 do 
local clientCode = getItem("client_codes", i)
message("Account = " .. clientCode)
end

**Comment by euvgub** [comment]
Я думал причина в том, что аргумент "index" приходил не в виде integer, поэтому client_codes отдавала ошибку, но другие таблицы показали, что это не так.

**Comment by Enfernuz** [comment]
Да, что-то странное определённо есть. У меня запрос getItem("client_codes", 0) выдаёт строку с номером счёта на фонде, например, а не таблицу. В доке по QLua написано, что функция возвращает таблицу. Т.е., по ходу, это ошибка в документации.
Добавлю костыль, обрабатывающий эту ситуацию: в случае, если getItem возвратил строку, буду возвращать в `table_row` таблицу вида
```{"singular_result": tostring(то_что_возвратила_функция)}```
