### ISSUE TITLE
{'error': {'message': "QLua-функция с именем 'CreateDataSource' не найдена.", 'code': 404}}

### ISSUE THREAD

**Issue by euvgub** [Enfernuz/quik-lua-rpc#23]
socket.send_string('{"method":"CreateDataSource", "args":{"class_code":"SPBFUT","sec_code":"SiH9","interval":"INTERVAL_TICK"}}')
message = socket.recv()
print(json.loads(message))
{'error': {'message': "QLua-функция с именем 'CreateDataSource' не найдена.", 'code': 404}}

**Comment by euvgub** [comment]
CreateDataSource.args.scheme.json
"$id": "https://github.com/Enfernuz/quik-lua-rpc/json/schema/datasource/CreateDataSource.args.scheme.json"

add blob?

"$id": "https://github.com/Enfernuz/quik-lua-rpc/blob/master/json/schema/datasource/CreateDataSource.args.scheme.json"

**Comment by Enfernuz** [comment]
Все методы работы с DataSource'ами должны быть с префиксом `datasource`: `datasource.CreateDataSource`, `datasource.Size`, `datasource.C`, ... Это сделано специально, чтобы выделить функции работы с источниками данных в отдельную группу. Надо бы уже оформить доку, чтобы не возникало таких проблем... :(

Насчёт корректной ссылки для id в схеме -- я думал над этим, но кто гарантирует, что схема всегда будет находиться по этому адресу? Хотя, конечно, это условность и вероятность изменения местоположения схемы мала, и можно забить и сделать для удобства.

**Comment by euvgub** [comment]
В procedure_wrappers.lua она прописана как datasource.CreateDataSource, поэтому так работает
socket.send_string('{"method":"datasource.CreateDataSource", "args":{"class_code":"SPBFUT","sec_code":"SiH9","interval":"INTERVAL_TICK"}}')
message = socket.recv()
print(json.loads(message))
{'result': {'datasource_uuid': '175d252a-fd72-4e01-ce60-88929a9b2aa9', 'is_error': False}}
