### ISSUE TITLE
getParamEx param_image в cp1251

### ISSUE THREAD

**Issue by euvgub** [Enfernuz/quik-lua-rpc#24]
getParamEx param_image в cp1251
Если результат getParamEx  получать socket.recv_string(encoding='cp1251'), то  param_image читается нормально. param_image это число с разделителями. напр 68 007 Если просто socket.recv(), то 
b'{"result":{"param_ex":{"param_type":"1","param_value":"66082.000000","result":"1","param_image":"66\xa0082"}}}'
print(json.loads(message)['result']['param_ex']['param_image'])
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 99: invalid start byte

**Comment by Enfernuz** [comment]
Спасибо, поправил.
