### ISSUE TITLE
При отсутствии всех обезличенных сделок вместо onAllTrade используем CreateDataSource?

### ISSUE THREAD

**Issue by euvgub** [Enfernuz/quik-lua-rpc#26]
При отсутствии всех обезличенных сделок (например, чтобы не грузить лишнюю инфу) вместо onAllTrade используем CreateDataSource - получаем datasource_uuid - посылаем datasource.SetUpdateCallback с аргументами datasource_uuid и f_cb_def? 
Непонятно, что такое и откуда берется "f_cb_def"?

**Comment by Enfernuz** [comment]
Это код функции-коллбэка на Lua в виде строки.

Из https://github.com/Enfernuz/quik-lua-rpc/blob/master/qlua/rpc/datasource/SetUpdateCallback.proto:
```
string f_cb_def = 2; // NB: формат функции: "function (NUMBER index, TABLE datasource) function_body end"
```
