### ISSUE TITLE
getCandlesByIndex json invalid table: mixed or invalid key types

### ISSUE THREAD

**Issue by slukin1** [Enfernuz/quik-lua-rpc#27]
Версия serde_protocol = json.
График открыт, графику присвоен tag "test_siu"
При отправке c любым числом значения "count", например
socket.send_string("{"method":"getCandlesByIndex", "args":{"tag":"test_siu","line":0,"first_candle":0,"count":10}}")
вылетает с ошибкой error("invalid table: mixed or invalid key types") из utils/json.lua т.е. не распознает "count" в качестве числа if type(k) ~= "number" then
Пропускает только если "count":0
В этом случае ожидаемо приходит пустая таблица
{"result":{"t":[],"l":"Si-9.19 [Price]","n":0}}
В getCandlesByIndex.args.scheme.json все правильно прописано
        "count": {
            "description": "Параметр count",
            "type": "integer",
            "minimum": 0
        }

**Comment by Enfernuz** [comment]
QUIK какую-то корявую таблицу в 't' передаёт в ответе:

![candles](https://user-images.githubusercontent.com/935535/60135455-6a969a00-97aa-11e9-8446-c84bf6ea5f2e.png)

Это если выбрать count = 1. При count > 1 свечи в таблице уже неидексированные, но вот такая, с индексом 0, есть всегда.

Посмотрю, что можно сделать.

**Comment by Enfernuz** [comment]
Поправил. Проверьте, пожалуйста.

**Comment by slukin1** [comment]
С измененным impl/procedure_wrappers.lua:
торговая сессия закрыта, коннект к брокеру не установлен. Но график с тегом "test_siu" отображается в Quik
Отсылаем
{"method": "getCandlesByIndex", "args": {"tag": "test_siu", "line": 0, "first_candle": 3700, "count": 1}}
Получаем с пустой таблицей t
{"result":{"t":[],"l":"","n":0}}
Т.е. ошибку invalid table: mixed or invalid key types уже не выдает, но и таблицу t не получает.
Попробую еще повторить в торговую сессию, а не на автономном графике

**Comment by Enfernuz** [comment]
Насколько я знаю, в QUIK есть ограничение на количество свечей на графике, и оно равно 3000. Т.е. first_candle = 3700 задавать нельзя. Результат, который Вы получаете, -- это то, что приходит из функции getCandlesByIndex в QUIK в случае задания ошибочных параметров.

https://broker.ru/help/quik/work-errors#26
https://forum.quik.ru/forum13/topic261/
https://forum.quik.ru/messages/forum13/message9719/topic1051/

**Comment by slukin1** [comment]
Убрал имя графика "tag":"". Заработало и при онлайн и при оффлайн.
{"method":"getCandlesByIndex", "args":{"tag":"","line":0,"first_candle":3700,"count":3}}
Приходит
{"result":{"t":[{"low":"63765","doesExist":1,"close":"63766","datetime":{"ms":0,"year":2019,"day":25,"week_day":2,"month":6,"sec":0,"hour":22,"min":5},"high":"63770","open":"63769","volume":"55"},{"low":"63751","doesExist":1,"close":"63757","datetime":{"ms":0,"year":2019,"day":25,"week_day":2,"month":6,"sec":0,"hour":22,"min":7},"high":"63760","open":"63760","volume":"519"},{"low":"63758","doesExist":1,"close":"63759","datetime":{"ms":0,"year":2019,"day":25,"week_day":2,"month":6,"sec":0,"hour":22,"min":6},"high":"63768","open":"63768","volume":"230"}],"l":"Si-9.19 [Price]","n":3}}
После исправленияimpl/procedure_wrappers.lua у меня ошибка рождалась от того, что был не сохранен идентификатор графика и при новом запуске Quik  "tag": "test_siu" не существовало.
Сейчас работает и при "first_candle" > 3000
Резюме: getCandlesByIndex дает возможность получать свечи с графика для тестирования даже в офлайн режиме квика

**Comment by slukin1** [comment]
Версия quik 7.27.2.1
