### ISSUE TITLE
AddLabel label_params просьба пример

### ISSUE THREAD

**Issue by slukin1** [Enfernuz/quik-lua-rpc#28]
AddLabel label_params просьба пример
График с иднетификатором "test_siu" открыт.
Посылаем два варианта добавления текстовой и графической метки
{"method":"AddLabel", "args":{"chart_tag":"test_siu","label_params":{"TEXT":"Test Label","YVALUE":64000,"DATE":20190626}}}
Текстовая метка не появляется
{"IMAGE_PATH":"C:\\Users\\tester\\Labels\\buy.bmp","YVALUE":64000,"DATE":20190626}}}
Метка-изображение не появляется

**Comment by slukin1** [comment]
Заработало при таком наборе:
{"method":"AddLabel", "args":{"chart_tag":"test_siu","label_params":{"TEXT":"TESTTT333678","IMAGE_PATH":"C:\\test\\Labels\\buy.bmp","YVALUE":63805,"DATE":20190626,"TIME":171800,"TRANSPARENCY":0,"TRANSPARENT_BACKGROUND":1,"HINT":"Text to show"}}}

**Comment by Enfernuz** [comment]
Возможно, связано с тем, что какие-то из параметров в таблице `label_params` обязательные. В документации к QLua, правда, ничего об обязательности не сказано.
Добавлю установку значений по умолчанию.

**Comment by Enfernuz** [comment]
По всей видимости, параметры `DATE` и `TIME` являются обязательными для всех интервалов (дневных в том числе).
