### ISSUE TITLE
python json getCandlesByIndex - данные приходят неупорядоченные по индексу, даты вразнобой

### ISSUE THREAD

**Issue by slukin1** [Enfernuz/quik-lua-rpc#31]
python json getCandlesByIndex - данные приходят неупорядоченные по индексу, даты вразнобой
Quik версия 7.27.2.1 Открыт график SiU9 Price Timeframe = Month
Данные свечей с графика приходят в случайном порядке, а не по индексу от 0-ой свечи до 23-й свечи.
'year': 2017, 'month': 9
'year': 2017, 'month': 11
'year': 2018, 'month': 1
'year': 2019, 'month': 4
'year': 2018, 'month': 12
'year': 2017, 'month': 10
```python  
socket.send_string('{"method":"getNumCandles","args":{"tag":"siu9_price_chart"}}')
number_of_candles = json.loads(socket.recv_string())['result']['num_candles']
socket.send_string('{"method":"getCandlesByIndex","args":{"tag":"siu9_price_chart","line":0,"first_candle":0,"count":%d}}' % (number_of_candles-1))
result = json.loads(socket.recv_string())
print(result)
{'result': {'t': [{'low': '64901', 'doesExist': 1, 'close': '65911', 'datetime': {'ms': 0, 'year': 2017, 'day': 1, 'week_day': 5, 'month': 9, 'sec': 0, 'hour': 0, 'min': 0}, 'high': '67482', 'open': '67482', 'volume': '146'}, {'low': '64311', 'doesExist': 1, 'close': '64500', 'datetime': {'ms': 0, 'year': 2017, 'day': 1, 'week_day': 3, 'month': 11, 'sec': 0, 'hour': 0, 'min': 0}, 'high': '66350', 'open': '64600', 'volume': '38'}, {'low': '60233', 'doesExist': 1, 'close': '61342', 'datetime': {'ms': 0, 'year': 2018, 'day': 1, 'week_day': 1, 'month': 1, 'sec': 0, 'hour': 0, 'min': 0}, 'high': '63000', 'open': '63000', 'volume': '40'}, ....... , {'low': '64984', 'doesExist': 1, 'close': '65861', 'datetime': {'ms': 0, 'year': 2019, 'day': 1, 'week_day': 1, 'month': 4, 'sec': 0, 'hour': 0, 'min': 0}, 'high': '67401', 'open': '67135', 'volume': '72814'}, {'low': '68500', 'doesExist': 1, 'close': '72117', 'datetime': {'ms': 0, 'year': 2018, 'day': 1, 'week_day': 6, 'month': 12, 'sec': 0, 'hour': 0, 'min': 0}, 'high': '72260', 'open': '68560', 'volume': '57455'}, {'low': '63694', 'doesExist': 1, 'close': '64500', 'datetime': {'ms': 0, 'year': 2017, 'day': 1, 'week_day': 0, 'month': 10, 'sec': 0, 'hour': 0, 'min': 0}, 'high': '65364', 'open': '65087', 'volume': '55'}], 'l': 'Si-9.19 [Price]', 'n': 23}}
```
Где-то по пути теряется индекс свечи.

Вроде нашлось решение: в procedure_wrappers.lua строка 471 
```lua
for i, candle in pairs(t) do 
```
заменить на 
```lua
for i, candle in ipairs(t) do 
```
Для сохранения порядка следования индекса заменить pairs на ipairs - правильно ли?

**Comment by Enfernuz** [comment]
Функция `getCandlesByIndex` на стороне QLua не назначает выходным свечам индекс. И свечи там идут вразнобой тоже по времени. У меня на терминале всё ещё 7 версии возвращается там таблица, в которой есть элемент с индексом [0], и остальные элементы без индексов. Как-то так это выглядит:
```
t = {
  [0] = {какая-то свеча, может быть, даже первая в требуемой выгрузке, но я не обратил внимание},
  {другая свеча},
  {другая свеча},
  ...
}
```

Соответственно, если итерироваться через `ipairs`, то свеча с ключом [0] не встретится. Поэтому я итерируюсь по этой таблице через `pairs` который уже не гарантирует никакого порядка, но даже если бы и гарантировал, то, как я уже сказал, в самом результате, судя по всему, порядок не предусмотрен. 

Поправьте, если я не прав, но и тогда, когда я писал обработчик, и сейчас у меня в этой таблице свечи не упорядочены (опять же, чтобы это увидеть, используются всё те же самые `pairs` и `ipairs`, а также библиотека `inspect`, которая наверняка использует те же самые ключевые слова при превращении таблицы в строку).

P.S. Спасибо, что подняли тему -- как раз поправил один маленький баг, когда легенда графика написана на русском языке (не было преобразования в UTF-8 при отдаче на сторону клиента).

**Comment by Enfernuz** [comment]
Практически, вижу два решения: либо сортировать результат на стороне сервиса (медленно, но удобно), либо сортировать результат на месте получения (скорее всего быстрее, но менее удобно). Лично я за то, чтобы оставить как есть, т.е. производить сортировку на стороне клиента, тем более если известно, что эта функция в QLua также не гарантирует порядок, т.е., с этой точки зрения, сервис не привносит никаких изменений и самодеятельности.

**Comment by slukin1** [comment]
Если исходить из того, что getCandlesByIndex полезна в основном тогда, когда торги не идут и можно неспеша тестировать на исторических данных, то сортировать результат на стороне клиента (медленно, но удобно) - вполне приемлемый вариант.

**Comment by slukin1** [comment]
Примерно так можно на клиенте отсортировать по времени свечи?
```python 
socket.send_string('{"method":"getCandlesByIndex","args":{"tag":"siu9_price_chart","line":0,"first_candle":0,"count":%d}}' % (num_candles))
result = json.loads(socket.recv_string())
data = result['result']['t']
for item in data:
        item['datetime'] = datetime.datetime(item['datetime']['year'], item['datetime']['month'], item['datetime']['day'], item['datetime']['hour'], item['datetime']['min'], item['datetime']['sec'], item['datetime']['ms'])
data = sorted(data, key=lambda k: k['datetime'])
print(data)
```

**Comment by Enfernuz** [comment]
Да, таким способом можно.

**Comment by slukin1** [comment]
Просто иллюстрация в продолжение темы, куда можно это дальше применить
```python
quotes = {}
quotes['open']=numpy.asarray([item['open'] for item in data])
quotes['close']=numpy.asarray([item['close'] for item in data])
quotes['high']=numpy.asarray([item['high'] for item in data])
quotes['low']=numpy.asarray([item['low'] for item in data])
quotes['datetime']=numpy.asarray([item['datetime'] for item in data])
fig, ax = plt.subplots(3, sharex=True)
candlestick2_ohlc(ax[0],quotes['open'],quotes['high'],quotes['low'],quotes['close'],width=0.6)
ax[0].xaxis.set_major_locator(ticker.MaxNLocator(6))
def chart_date(x,pos):
    try:
        return quotes['datetime'][int(x)]
    except IndexError:
        return ''
ax[0].xaxis.set_major_formatter(ticker.FuncFormatter(chart_date))
fig.autofmt_xdate()
fig.tight_layout()
quotes['close'] = numpy.array([float(x) for x in quotes['close']])
sma = talib.SMA(quotes['close'], timeperiod=50)
ax[0].plot(sma)
ema = talib.EMA(quotes['close'], timeperiod=20)
ax[0].plot(ema)
macd, macdsignal, macdhist = talib.MACD(quotes['close'], fastperiod=12, slowperiod=26, signalperiod=9)
ax[1].plot(macd, color="y")
ax[1].plot(macdsignal)
hist_data = []
for elem in macdhist:
    if not numpy.isnan(elem):
        v = 0 if numpy.isnan(elem) else elem
        hist_data.append(v*100)
ax[2].fill_between([x for x in range(len(macdhist))], 0,macdhist)
plt.show()
```
