### ISSUE TITLE
Вместо времени в структурах отдаваемых getItem отсылаются id таблицы с временем

### ISSUE THREAD

**Issue by dsabdrashitov** [Enfernuz/quik-lua-rpc#35]
В обработке функции getItem результат пропускается через функцию to_string_string_table(), которая значения всех полей приводит к строкам через tostring(). Однако время в таблицах Quik обычно представлено структурой {year, month, day, week_day, hour, min, sec, ms, mcs}. Функция tostring() же от такой таблицы возвращает лишь строку типа 'table: 115F2B78', т.е. id объекта вместо его содержимого. Что делает невозможным через getItem получать значение времени в колонках таких таблиц, например, как ORDERS или TRADES.

**Comment by Enfernuz** [comment]
Да, спасибо, что заметили этот момент!
Думаю, целесообразнее будет конвертировать все встреченные таблицы в точно такие же таблицы (строка-ключ -- строка-значение). Т.к. всем не угодишь (кому в определённом строковом формате нужно, кому и в табличном норм), то этот вариант выглядит как золотая середина.

Пофиксил в c6f7061.
