### ISSUE TITLE
Скрипт отъедает 30% процессорного времени на холостом ходу.

### ISSUE THREAD

**Issue by gonsalez-ru** [Enfernuz/quik-lua-rpc#51]
Здравствуйте!
После запуска скрипта нагрузка на процессор подскакивает на 30%. Никаких запросов в это время не обрабатывается. Можно ли с этим бороться? Какие средства диагностики/отладки/протоколирования можете посоветовать? 
Quik 8.8.4.3

**Comment by demen777** [comment]
Мне помогло добавление небольшого sleep в poller.lua

```lua
function poller_mt:start()
	self.is_running = true
	while self.is_running do
		local status, err = self:poll(-1)
                sleep(10)
		if not status then
			return false, err
		end
	end
	return true
end
```

Sleep используется от quik

**Comment by gonsalez-ru** [comment]
> 
> Мне помогло добавление небольшого sleep в poller.lua
> 
А я не ограничу этим производительность сервиса в 100 сообщений в секунду? (1000мс/10мс)
Может быть паузу нужно делать динамической в зависимости от трафика?

**Comment by Enfernuz** [comment]
Да, кстати, меня тоже волновала эта проблема. Компьютер воет, будто крипту майнит :) Были подозрения, что где-то неблокирующее чтение происходит, но я тогда так и не нашёл, где.

Судя по коду Lua-шного ZMQ-поллера, он как раз должен блочиться, если нет данных.
http://api.zeromq.org/2-1:zmq-poll
>If the value of timeout is -1, zmq_poll() shall block indefinitely until a requested event has occurred on at least one zmq_pollitem_t. The resolution of timeout is 1 millisecond.

В `poller.lua` как раз -1 и передаётся...

**Comment by demen777** [comment]
> > Мне помогло добавление небольшого sleep в poller.lua
> 
> А я не ограничу этим производительность сервиса в 100 сообщений в секунду? (1000мс/10мс)
> Может быть паузу нужно делать динамической в зависимости от трафика?

Можно сделать sleep(1) - эффект будет практически тем же что и sleep(10)

**Comment by demen777** [comment]
> Да, кстати, меня тоже волновала эта проблема. Компьютер воет, будто крипту майнит :) Были подозрения, что где-то неблокирующее чтение происходит, но я тогда так и не нашёл, где.
> 
> Судя по коду Lua-шного ZMQ-поллера, он как раз должен блочиться, если нет данных.
> http://api.zeromq.org/2-1:zmq-poll
> 
> > If the value of timeout is -1, zmq_poll() shall block indefinitely until a requested event has occurred on at least one zmq_pollitem_t. The resolution of timeout is 1 millisecond.
> 
> В `poller.lua` как раз -1 и передаётся...

Возможно на Windows из-за специфики сокетов оно урезано реализовано.

**Comment by Enfernuz** [comment]
Я давно подозревал, что проставил не тот тип эвента в поллинге для PUB-сокета. Сейчас наконец-то почитал и врубился, что вместо POLLOUT (эвент на возможность отправки исходящих данных) надо использовать POLLIN (эвент на возможность прочитать входящие данные).
Попробуйте потестить. У меня после фикса ушла проблема с повышенным использованием ЦПУ.
