### ISSUE TITLE
Ошибка после создания OTC заявки

### ISSUE THREAD

**Issue by gonsalez-ru** [Enfernuz/quik-lua-rpc#52]
...lua\quik-lua-rpc/impl\protobuf_event_data_serializer.lua:25: bad argument #2 to 'encode' (string expected for field 'uid', got number)

**Comment by Enfernuz** [comment]
Интересно... Судя по текущей документации QLua, нигде поле `uid` не имеет тип `string` -- везде NUMBER.
Можете идентифицировать эвент, при получении которого возникает ошибка? ON_TRADE?

**Comment by Enfernuz** [comment]
Если добавить
```
order.uid = tostring(order.uid)
```
[сюда](https://github.com/Enfernuz/quik-lua-rpc/blob/2f281e865b13553fc60e3b53c95a8e5688fc641b/impl/protobuf_event_data_serializer.lua#L89), то всё нормально?

**Comment by gonsalez-ru** [comment]
> 
> 
> Если добавить
> 
> ```
> order.uid = tostring(order.uid)
> ```
> 
> [сюда](https://github.com/Enfernuz/quik-lua-rpc/blob/2f281e865b13553fc60e3b53c95a8e5688fc641b/impl/protobuf_event_data_serializer.lua#L89), то всё нормально?

Да, тогда все Ок.

**Comment by Enfernuz** [comment]
Поправил. Спасибо!
