### ISSUE TITLE
У меня периодически падает quik с ошибкой  Exception code: 0xc0000374

### ISSUE THREAD

**Issue by gojmpz** [Enfernuz/quik-lua-rpc#57]
У меня операционная система Debian Buster, quik работает в VirtualBox на windows 10. Иногда просто падает, когда запущен quik-lua-rpc. Воспроизводится, например, если послать getSecurityInfo_pb2 без пауз раз 200 подряд.
Ошибка в системном журнале следующая:
![quik_error1](https://user-images.githubusercontent.com/886064/96899787-82c01b80-14bb-11eb-8775-fcbe5a1f0c65.png)
![quik_error2](https://user-images.githubusercontent.com/886064/96899788-8358b200-14bb-11eb-8c06-6922dd1fc091.png)

Кто-то с таким сталкивался?

**Comment by gojmpz** [comment]
Добавив паузу в одну миллисекунду между запросами в обработчике events, проблема, вроде, пропала

**Comment by gojmpz** [comment]
Достаточно долго искал и понимал проблему, она возникала очень редко, в момент какого-либо реквеста. На pub-событиях проблем не было. 
У меня постоянно идёт поток обезличенных и сделок, параллельно совершаются сделки.
Сделал два кофига для скриптов: один на pub, другой на req, чтобы разделить потоки и проблема ушла (уже 10 дней не было ни одной ошибки.)

**Comment by aesirot** [comment]
А у вас при включеном PUB Quik начинает агрессивно грузить CPU ? 
У меня явно 1 ядро грузит - причем даже при отсутствии публикаций со стороны Quik.
Какая-то проблема в lzmq видимо

**Comment by gojmpz** [comment]
У меня quik живёт в virtualbox, выделено 2 ядра, загрузка на процессор не более 10% во время торговой сессии с потоком обезличенных сделок.

**Comment by gojmpz** [comment]
Проблема решена:
`Сделал два кофига для скриптов: один на pub, другой на req, чтобы разделить потоки и проблема ушла.
